#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ProyectoAcme")]
	public partial class ProyectoAcmeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InserttblCapacitacion(tblCapacitacion instance);
    partial void UpdatetblCapacitacion(tblCapacitacion instance);
    partial void DeletetblCapacitacion(tblCapacitacion instance);
    partial void InserttblCargo(tblCargo instance);
    partial void UpdatetblCargo(tblCargo instance);
    partial void DeletetblCargo(tblCargo instance);
    partial void InserttblDepartamento(tblDepartamento instance);
    partial void UpdatetblDepartamento(tblDepartamento instance);
    partial void DeletetblDepartamento(tblDepartamento instance);
    partial void InserttblDtosFamilia(tblDtosFamilia instance);
    partial void UpdatetblDtosFamilia(tblDtosFamilia instance);
    partial void DeletetblDtosFamilia(tblDtosFamilia instance);
    partial void InserttblEmpleado(tblEmpleado instance);
    partial void UpdatetblEmpleado(tblEmpleado instance);
    partial void DeletetblEmpleado(tblEmpleado instance);
    partial void InserttblEmpresa(tblEmpresa instance);
    partial void UpdatetblEmpresa(tblEmpresa instance);
    partial void DeletetblEmpresa(tblEmpresa instance);
    partial void InserttblReferencia(tblReferencia instance);
    partial void UpdatetblReferencia(tblReferencia instance);
    partial void DeletetblReferencia(tblReferencia instance);
    partial void InsertTbl_Persona(Tbl_Persona instance);
    partial void UpdateTbl_Persona(Tbl_Persona instance);
    partial void DeleteTbl_Persona(Tbl_Persona instance);
    partial void InsertTbl_Usuario(Tbl_Usuario instance);
    partial void UpdateTbl_Usuario(Tbl_Usuario instance);
    partial void DeleteTbl_Usuario(Tbl_Usuario instance);
    #endregion
		
		public ProyectoAcmeDataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.ProyectoAcmeConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ProyectoAcmeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProyectoAcmeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProyectoAcmeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProyectoAcmeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Paciente> Paciente
		{
			get
			{
				return this.GetTable<Paciente>();
			}
		}
		
		public System.Data.Linq.Table<Persona> Persona
		{
			get
			{
				return this.GetTable<Persona>();
			}
		}
		
		public System.Data.Linq.Table<tblCapacitacion> tblCapacitacion
		{
			get
			{
				return this.GetTable<tblCapacitacion>();
			}
		}
		
		public System.Data.Linq.Table<tblCargo> tblCargo
		{
			get
			{
				return this.GetTable<tblCargo>();
			}
		}
		
		public System.Data.Linq.Table<tblDepartamento> tblDepartamento
		{
			get
			{
				return this.GetTable<tblDepartamento>();
			}
		}
		
		public System.Data.Linq.Table<tblDtosFamilia> tblDtosFamilia
		{
			get
			{
				return this.GetTable<tblDtosFamilia>();
			}
		}
		
		public System.Data.Linq.Table<tblEmpleado> tblEmpleado
		{
			get
			{
				return this.GetTable<tblEmpleado>();
			}
		}
		
		public System.Data.Linq.Table<tblEmpresa> tblEmpresa
		{
			get
			{
				return this.GetTable<tblEmpresa>();
			}
		}
		
		public System.Data.Linq.Table<tblReferencia> tblReferencia
		{
			get
			{
				return this.GetTable<tblReferencia>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Persona> Tbl_Persona
		{
			get
			{
				return this.GetTable<Tbl_Persona>();
			}
		}
		
		public System.Data.Linq.Table<Tbl_Usuario> Tbl_Usuario
		{
			get
			{
				return this.GetTable<Tbl_Usuario>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.editarCapacitacion")]
		public int editarCapacitacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fechaIni, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fechaFin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCapacitacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion, fechaIni, fechaFin, idEmpleado, idCapacitacion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.editarCargo")]
		public int editarCargo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCargo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion, idCargo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.editarDepartamento")]
		public int editarDepartamento([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idDepartamento)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion, idDepartamento);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.editarDtosFamilia")]
		public int editarDtosFamilia([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string nombrePaterno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string nombreMaterno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idDtosFamilia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombrePaterno, nombreMaterno, direccion, telefono, idEmpleado, idDtosFamilia);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.editarEmpleado")]
		public int editarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string contra, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idDepartamento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCargo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpleado, nombres, direccion, correo, cedula, telefono, contra, idDepartamento, idCargo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.editarEmpresa")]
		public int editarEmpresa([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idDepartamento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idEmpresa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, direccion, idDepartamento, idEmpresa);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EditarProductos", IsComposable=true)]
		public object EditarProductos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string desc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> stock, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, desc, precio, stock, id).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.editarReferencia")]
		public int editarReferencia([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idReferencia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tipoReferencia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idEmpleado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idReferencia, nombres, telefono, tipoReferencia, idEmpleado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarCapacitacion")]
		public int eliminarCapacitacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCapacitacion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCapacitacion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarCargo")]
		public int eliminarCargo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCargo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCargo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarDepartamento")]
		public int eliminarDepartamento([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idDepartamento)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDepartamento);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarDtosFamilia")]
		public int eliminarDtosFamilia([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idDtosFamilia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDtosFamilia);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarEmpleado")]
		public int eliminarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idEmpleado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpleado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarEmpresa")]
		public int eliminarEmpresa([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idEmpresa)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpresa);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EliminarProductos", IsComposable=true)]
		public object EliminarProductos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarReferencia")]
		public int eliminarReferencia([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idReferencia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idReferencia);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarCapacitacion")]
		public int insertarCapacitacion([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fechaIni, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fechaFin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idEmpleado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion, fechaIni, fechaFin, idEmpleado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarCargo")]
		public int insertarCargo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarDepartamento")]
		public int insertarDepartamento([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarDtosFamilia")]
		public int insertarDtosFamilia([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string nombrePaterno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string nombreMaterno, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idEmpleado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombrePaterno, nombreMaterno, direccion, telefono, idEmpleado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarEmpleado")]
		public int insertarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string correo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string contra, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idDepartamento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idCargo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombres, direccion, correo, cedula, telefono, contra, idDepartamento, idCargo);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarEmpresa")]
		public int insertarEmpresa([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idDepartamento)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, direccion, idDepartamento);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarProductos", IsComposable=true)]
		public object InsertarProductos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string desc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> stock)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, desc, precio, stock).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarReferencia")]
		public int insertarReferencia([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string nombres, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tipoReferencia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idEmpleado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombres, telefono, tipoReferencia, idEmpleado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrarCapacitacion")]
		public ISingleResult<mostrarCapacitacionResult> mostrarCapacitacion()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<mostrarCapacitacionResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrarCargo")]
		public ISingleResult<mostrarCargoResult> mostrarCargo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<mostrarCargoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrarCartgo")]
		public ISingleResult<mostrarCartgoResult> mostrarCartgo()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<mostrarCartgoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrarDepartamento")]
		public ISingleResult<mostrarDepartamentoResult> mostrarDepartamento()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<mostrarDepartamentoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrarDtosFamilia")]
		public ISingleResult<mostrarDtosFamiliaResult> mostrarDtosFamilia()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<mostrarDtosFamiliaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrarEmpleado")]
		public ISingleResult<mostrarEmpleadoResult> mostrarEmpleado()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<mostrarEmpleadoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrarEmpresa")]
		public ISingleResult<mostrarEmpresaResult> mostrarEmpresa()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<mostrarEmpresaResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Paciente")]
	public partial class Paciente
	{
		
		private int _paci_id;
		
		private string _paci_peso;
		
		private string _paci_tiposangre;
		
		private string _paci_estatura;
		
		private string _paci_sintoma;
		
		private int _per_id;
		
		public Paciente()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paci_id", DbType="Int NOT NULL")]
		public int paci_id
		{
			get
			{
				return this._paci_id;
			}
			set
			{
				if ((this._paci_id != value))
				{
					this._paci_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paci_peso", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string paci_peso
		{
			get
			{
				return this._paci_peso;
			}
			set
			{
				if ((this._paci_peso != value))
				{
					this._paci_peso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paci_tiposangre", DbType="VarChar(10)")]
		public string paci_tiposangre
		{
			get
			{
				return this._paci_tiposangre;
			}
			set
			{
				if ((this._paci_tiposangre != value))
				{
					this._paci_tiposangre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paci_estatura", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string paci_estatura
		{
			get
			{
				return this._paci_estatura;
			}
			set
			{
				if ((this._paci_estatura != value))
				{
					this._paci_estatura = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paci_sintoma", DbType="NChar(10)")]
		public string paci_sintoma
		{
			get
			{
				return this._paci_sintoma;
			}
			set
			{
				if ((this._paci_sintoma != value))
				{
					this._paci_sintoma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_id", DbType="Int NOT NULL")]
		public int per_id
		{
			get
			{
				return this._per_id;
			}
			set
			{
				if ((this._per_id != value))
				{
					this._per_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Persona")]
	public partial class Persona
	{
		
		private int _per_id;
		
		private string _per_nombres;
		
		private string _per_apellidos;
		
		private System.Nullable<int> _per_cedula;
		
		private string _per_email;
		
		private string _per_telefono;
		
		private System.DateTime _per_fechanacimiento;
		
		private string _per_genero;
		
		private string _per_direccion;
		
		private string _per_estado;
		
		private System.DateTime _per_fechaCreacion;
		
		private string _per_usuario;
		
		private string _per_contrasenia;
		
		private int _id_tipousu;
		
		public Persona()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_id", DbType="Int NOT NULL")]
		public int per_id
		{
			get
			{
				return this._per_id;
			}
			set
			{
				if ((this._per_id != value))
				{
					this._per_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_nombres", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string per_nombres
		{
			get
			{
				return this._per_nombres;
			}
			set
			{
				if ((this._per_nombres != value))
				{
					this._per_nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_apellidos", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string per_apellidos
		{
			get
			{
				return this._per_apellidos;
			}
			set
			{
				if ((this._per_apellidos != value))
				{
					this._per_apellidos = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_cedula", DbType="Int")]
		public System.Nullable<int> per_cedula
		{
			get
			{
				return this._per_cedula;
			}
			set
			{
				if ((this._per_cedula != value))
				{
					this._per_cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string per_email
		{
			get
			{
				return this._per_email;
			}
			set
			{
				if ((this._per_email != value))
				{
					this._per_email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_telefono", DbType="NChar(10)")]
		public string per_telefono
		{
			get
			{
				return this._per_telefono;
			}
			set
			{
				if ((this._per_telefono != value))
				{
					this._per_telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_fechanacimiento", DbType="Date NOT NULL")]
		public System.DateTime per_fechanacimiento
		{
			get
			{
				return this._per_fechanacimiento;
			}
			set
			{
				if ((this._per_fechanacimiento != value))
				{
					this._per_fechanacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_genero", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string per_genero
		{
			get
			{
				return this._per_genero;
			}
			set
			{
				if ((this._per_genero != value))
				{
					this._per_genero = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_direccion", DbType="VarChar(100)")]
		public string per_direccion
		{
			get
			{
				return this._per_direccion;
			}
			set
			{
				if ((this._per_direccion != value))
				{
					this._per_direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_estado", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string per_estado
		{
			get
			{
				return this._per_estado;
			}
			set
			{
				if ((this._per_estado != value))
				{
					this._per_estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_fechaCreacion", DbType="Date NOT NULL")]
		public System.DateTime per_fechaCreacion
		{
			get
			{
				return this._per_fechaCreacion;
			}
			set
			{
				if ((this._per_fechaCreacion != value))
				{
					this._per_fechaCreacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string per_usuario
		{
			get
			{
				return this._per_usuario;
			}
			set
			{
				if ((this._per_usuario != value))
				{
					this._per_usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_contrasenia", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string per_contrasenia
		{
			get
			{
				return this._per_contrasenia;
			}
			set
			{
				if ((this._per_contrasenia != value))
				{
					this._per_contrasenia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipousu", DbType="Int NOT NULL")]
		public int id_tipousu
		{
			get
			{
				return this._id_tipousu;
			}
			set
			{
				if ((this._id_tipousu != value))
				{
					this._id_tipousu = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCapacitacion")]
	public partial class tblCapacitacion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCapacitacion;
		
		private string _descripcion;
		
		private string _fechaIni;
		
		private string _fechaFin;
		
		private System.Nullable<int> _idEmpleado;
		
		private EntityRef<tblEmpleado> _tblEmpleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCapacitacionChanging(int value);
    partial void OnidCapacitacionChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnfechaIniChanging(string value);
    partial void OnfechaIniChanged();
    partial void OnfechaFinChanging(string value);
    partial void OnfechaFinChanged();
    partial void OnidEmpleadoChanging(System.Nullable<int> value);
    partial void OnidEmpleadoChanged();
    #endregion
		
		public tblCapacitacion()
		{
			this._tblEmpleado = default(EntityRef<tblEmpleado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCapacitacion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idCapacitacion
		{
			get
			{
				return this._idCapacitacion;
			}
			set
			{
				if ((this._idCapacitacion != value))
				{
					this.OnidCapacitacionChanging(value);
					this.SendPropertyChanging();
					this._idCapacitacion = value;
					this.SendPropertyChanged("idCapacitacion");
					this.OnidCapacitacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(100)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaIni", DbType="NVarChar(100)")]
		public string fechaIni
		{
			get
			{
				return this._fechaIni;
			}
			set
			{
				if ((this._fechaIni != value))
				{
					this.OnfechaIniChanging(value);
					this.SendPropertyChanging();
					this._fechaIni = value;
					this.SendPropertyChanged("fechaIni");
					this.OnfechaIniChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaFin", DbType="NVarChar(100)")]
		public string fechaFin
		{
			get
			{
				return this._fechaFin;
			}
			set
			{
				if ((this._fechaFin != value))
				{
					this.OnfechaFinChanging(value);
					this.SendPropertyChanging();
					this._fechaFin = value;
					this.SendPropertyChanged("fechaFin");
					this.OnfechaFinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpleado", DbType="Int")]
		public System.Nullable<int> idEmpleado
		{
			get
			{
				return this._idEmpleado;
			}
			set
			{
				if ((this._idEmpleado != value))
				{
					if (this._tblEmpleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._idEmpleado = value;
					this.SendPropertyChanged("idEmpleado");
					this.OnidEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEmpleado_tblCapacitacion", Storage="_tblEmpleado", ThisKey="idEmpleado", OtherKey="idEmpleado", IsForeignKey=true)]
		public tblEmpleado tblEmpleado
		{
			get
			{
				return this._tblEmpleado.Entity;
			}
			set
			{
				tblEmpleado previousValue = this._tblEmpleado.Entity;
				if (((previousValue != value) 
							|| (this._tblEmpleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblEmpleado.Entity = null;
						previousValue.tblCapacitacion.Remove(this);
					}
					this._tblEmpleado.Entity = value;
					if ((value != null))
					{
						value.tblCapacitacion.Add(this);
						this._idEmpleado = value.idEmpleado;
					}
					else
					{
						this._idEmpleado = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblEmpleado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCargo")]
	public partial class tblCargo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCargo;
		
		private string _descripcion;
		
		private EntitySet<tblEmpleado> _tblEmpleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCargoChanging(int value);
    partial void OnidCargoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public tblCargo()
		{
			this._tblEmpleado = new EntitySet<tblEmpleado>(new Action<tblEmpleado>(this.attach_tblEmpleado), new Action<tblEmpleado>(this.detach_tblEmpleado));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCargo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idCargo
		{
			get
			{
				return this._idCargo;
			}
			set
			{
				if ((this._idCargo != value))
				{
					this.OnidCargoChanging(value);
					this.SendPropertyChanging();
					this._idCargo = value;
					this.SendPropertyChanged("idCargo");
					this.OnidCargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(50)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCargo_tblEmpleado", Storage="_tblEmpleado", ThisKey="idCargo", OtherKey="idCargo")]
		public EntitySet<tblEmpleado> tblEmpleado
		{
			get
			{
				return this._tblEmpleado;
			}
			set
			{
				this._tblEmpleado.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblEmpleado(tblEmpleado entity)
		{
			this.SendPropertyChanging();
			entity.tblCargo = this;
		}
		
		private void detach_tblEmpleado(tblEmpleado entity)
		{
			this.SendPropertyChanging();
			entity.tblCargo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDepartamento")]
	public partial class tblDepartamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDepartamento;
		
		private string _descripcion;
		
		private EntitySet<tblEmpleado> _tblEmpleado;
		
		private EntitySet<tblEmpresa> _tblEmpresa;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDepartamentoChanging(int value);
    partial void OnidDepartamentoChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public tblDepartamento()
		{
			this._tblEmpleado = new EntitySet<tblEmpleado>(new Action<tblEmpleado>(this.attach_tblEmpleado), new Action<tblEmpleado>(this.detach_tblEmpleado));
			this._tblEmpresa = new EntitySet<tblEmpresa>(new Action<tblEmpresa>(this.attach_tblEmpresa), new Action<tblEmpresa>(this.detach_tblEmpresa));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepartamento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idDepartamento
		{
			get
			{
				return this._idDepartamento;
			}
			set
			{
				if ((this._idDepartamento != value))
				{
					this.OnidDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._idDepartamento = value;
					this.SendPropertyChanged("idDepartamento");
					this.OnidDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(50)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDepartamento_tblEmpleado", Storage="_tblEmpleado", ThisKey="idDepartamento", OtherKey="idDepartamento")]
		public EntitySet<tblEmpleado> tblEmpleado
		{
			get
			{
				return this._tblEmpleado;
			}
			set
			{
				this._tblEmpleado.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDepartamento_tblEmpresa", Storage="_tblEmpresa", ThisKey="idDepartamento", OtherKey="idDepartamento")]
		public EntitySet<tblEmpresa> tblEmpresa
		{
			get
			{
				return this._tblEmpresa;
			}
			set
			{
				this._tblEmpresa.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblEmpleado(tblEmpleado entity)
		{
			this.SendPropertyChanging();
			entity.tblDepartamento = this;
		}
		
		private void detach_tblEmpleado(tblEmpleado entity)
		{
			this.SendPropertyChanging();
			entity.tblDepartamento = null;
		}
		
		private void attach_tblEmpresa(tblEmpresa entity)
		{
			this.SendPropertyChanging();
			entity.tblDepartamento = this;
		}
		
		private void detach_tblEmpresa(tblEmpresa entity)
		{
			this.SendPropertyChanging();
			entity.tblDepartamento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDtosFamilia")]
	public partial class tblDtosFamilia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idDtosFamilia;
		
		private string _nombrePaterno;
		
		private string _nombreMaterno;
		
		private string _direccion;
		
		private System.Nullable<int> _telefono;
		
		private System.Nullable<int> _idEmpleado;
		
		private EntityRef<tblEmpleado> _tblEmpleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidDtosFamiliaChanging(int value);
    partial void OnidDtosFamiliaChanged();
    partial void OnnombrePaternoChanging(string value);
    partial void OnnombrePaternoChanged();
    partial void OnnombreMaternoChanging(string value);
    partial void OnnombreMaternoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OntelefonoChanging(System.Nullable<int> value);
    partial void OntelefonoChanged();
    partial void OnidEmpleadoChanging(System.Nullable<int> value);
    partial void OnidEmpleadoChanged();
    #endregion
		
		public tblDtosFamilia()
		{
			this._tblEmpleado = default(EntityRef<tblEmpleado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDtosFamilia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idDtosFamilia
		{
			get
			{
				return this._idDtosFamilia;
			}
			set
			{
				if ((this._idDtosFamilia != value))
				{
					this.OnidDtosFamiliaChanging(value);
					this.SendPropertyChanging();
					this._idDtosFamilia = value;
					this.SendPropertyChanged("idDtosFamilia");
					this.OnidDtosFamiliaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombrePaterno", DbType="NVarChar(100)")]
		public string nombrePaterno
		{
			get
			{
				return this._nombrePaterno;
			}
			set
			{
				if ((this._nombrePaterno != value))
				{
					this.OnnombrePaternoChanging(value);
					this.SendPropertyChanging();
					this._nombrePaterno = value;
					this.SendPropertyChanged("nombrePaterno");
					this.OnnombrePaternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreMaterno", DbType="NVarChar(100)")]
		public string nombreMaterno
		{
			get
			{
				return this._nombreMaterno;
			}
			set
			{
				if ((this._nombreMaterno != value))
				{
					this.OnnombreMaternoChanging(value);
					this.SendPropertyChanging();
					this._nombreMaterno = value;
					this.SendPropertyChanged("nombreMaterno");
					this.OnnombreMaternoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(100)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="Int")]
		public System.Nullable<int> telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpleado", DbType="Int")]
		public System.Nullable<int> idEmpleado
		{
			get
			{
				return this._idEmpleado;
			}
			set
			{
				if ((this._idEmpleado != value))
				{
					if (this._tblEmpleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._idEmpleado = value;
					this.SendPropertyChanged("idEmpleado");
					this.OnidEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEmpleado_tblDtosFamilia", Storage="_tblEmpleado", ThisKey="idEmpleado", OtherKey="idEmpleado", IsForeignKey=true)]
		public tblEmpleado tblEmpleado
		{
			get
			{
				return this._tblEmpleado.Entity;
			}
			set
			{
				tblEmpleado previousValue = this._tblEmpleado.Entity;
				if (((previousValue != value) 
							|| (this._tblEmpleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblEmpleado.Entity = null;
						previousValue.tblDtosFamilia.Remove(this);
					}
					this._tblEmpleado.Entity = value;
					if ((value != null))
					{
						value.tblDtosFamilia.Add(this);
						this._idEmpleado = value.idEmpleado;
					}
					else
					{
						this._idEmpleado = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblEmpleado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblEmpleado")]
	public partial class tblEmpleado : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idEmpleado;
		
		private string _nombres;
		
		private string _direccion;
		
		private string _correo;
		
		private System.Nullable<int> _cedula;
		
		private System.Nullable<int> _telefono;
		
		private string _contra;
		
		private System.Nullable<int> _idDepartamento;
		
		private System.Nullable<int> _idCargo;
		
		private EntitySet<tblCapacitacion> _tblCapacitacion;
		
		private EntitySet<tblDtosFamilia> _tblDtosFamilia;
		
		private EntitySet<tblReferencia> _tblReferencia;
		
		private EntityRef<tblCargo> _tblCargo;
		
		private EntityRef<tblDepartamento> _tblDepartamento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEmpleadoChanging(int value);
    partial void OnidEmpleadoChanged();
    partial void OnnombresChanging(string value);
    partial void OnnombresChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OncedulaChanging(System.Nullable<int> value);
    partial void OncedulaChanged();
    partial void OntelefonoChanging(System.Nullable<int> value);
    partial void OntelefonoChanged();
    partial void OncontraChanging(string value);
    partial void OncontraChanged();
    partial void OnidDepartamentoChanging(System.Nullable<int> value);
    partial void OnidDepartamentoChanged();
    partial void OnidCargoChanging(System.Nullable<int> value);
    partial void OnidCargoChanged();
    #endregion
		
		public tblEmpleado()
		{
			this._tblCapacitacion = new EntitySet<tblCapacitacion>(new Action<tblCapacitacion>(this.attach_tblCapacitacion), new Action<tblCapacitacion>(this.detach_tblCapacitacion));
			this._tblDtosFamilia = new EntitySet<tblDtosFamilia>(new Action<tblDtosFamilia>(this.attach_tblDtosFamilia), new Action<tblDtosFamilia>(this.detach_tblDtosFamilia));
			this._tblReferencia = new EntitySet<tblReferencia>(new Action<tblReferencia>(this.attach_tblReferencia), new Action<tblReferencia>(this.detach_tblReferencia));
			this._tblCargo = default(EntityRef<tblCargo>);
			this._tblDepartamento = default(EntityRef<tblDepartamento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpleado", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idEmpleado
		{
			get
			{
				return this._idEmpleado;
			}
			set
			{
				if ((this._idEmpleado != value))
				{
					this.OnidEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._idEmpleado = value;
					this.SendPropertyChanged("idEmpleado");
					this.OnidEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="NVarChar(100)")]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this.OnnombresChanging(value);
					this.SendPropertyChanging();
					this._nombres = value;
					this.SendPropertyChanged("nombres");
					this.OnnombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(100)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="NVarChar(100)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="Int")]
		public System.Nullable<int> cedula
		{
			get
			{
				return this._cedula;
			}
			set
			{
				if ((this._cedula != value))
				{
					this.OncedulaChanging(value);
					this.SendPropertyChanging();
					this._cedula = value;
					this.SendPropertyChanged("cedula");
					this.OncedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="Int")]
		public System.Nullable<int> telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contra", DbType="NVarChar(100)")]
		public string contra
		{
			get
			{
				return this._contra;
			}
			set
			{
				if ((this._contra != value))
				{
					this.OncontraChanging(value);
					this.SendPropertyChanging();
					this._contra = value;
					this.SendPropertyChanged("contra");
					this.OncontraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepartamento", DbType="Int")]
		public System.Nullable<int> idDepartamento
		{
			get
			{
				return this._idDepartamento;
			}
			set
			{
				if ((this._idDepartamento != value))
				{
					if (this._tblDepartamento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._idDepartamento = value;
					this.SendPropertyChanged("idDepartamento");
					this.OnidDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCargo", DbType="Int")]
		public System.Nullable<int> idCargo
		{
			get
			{
				return this._idCargo;
			}
			set
			{
				if ((this._idCargo != value))
				{
					if (this._tblCargo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidCargoChanging(value);
					this.SendPropertyChanging();
					this._idCargo = value;
					this.SendPropertyChanged("idCargo");
					this.OnidCargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEmpleado_tblCapacitacion", Storage="_tblCapacitacion", ThisKey="idEmpleado", OtherKey="idEmpleado")]
		public EntitySet<tblCapacitacion> tblCapacitacion
		{
			get
			{
				return this._tblCapacitacion;
			}
			set
			{
				this._tblCapacitacion.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEmpleado_tblDtosFamilia", Storage="_tblDtosFamilia", ThisKey="idEmpleado", OtherKey="idEmpleado")]
		public EntitySet<tblDtosFamilia> tblDtosFamilia
		{
			get
			{
				return this._tblDtosFamilia;
			}
			set
			{
				this._tblDtosFamilia.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEmpleado_tblReferencia", Storage="_tblReferencia", ThisKey="idEmpleado", OtherKey="idEmpleado")]
		public EntitySet<tblReferencia> tblReferencia
		{
			get
			{
				return this._tblReferencia;
			}
			set
			{
				this._tblReferencia.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCargo_tblEmpleado", Storage="_tblCargo", ThisKey="idCargo", OtherKey="idCargo", IsForeignKey=true)]
		public tblCargo tblCargo
		{
			get
			{
				return this._tblCargo.Entity;
			}
			set
			{
				tblCargo previousValue = this._tblCargo.Entity;
				if (((previousValue != value) 
							|| (this._tblCargo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblCargo.Entity = null;
						previousValue.tblEmpleado.Remove(this);
					}
					this._tblCargo.Entity = value;
					if ((value != null))
					{
						value.tblEmpleado.Add(this);
						this._idCargo = value.idCargo;
					}
					else
					{
						this._idCargo = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblCargo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDepartamento_tblEmpleado", Storage="_tblDepartamento", ThisKey="idDepartamento", OtherKey="idDepartamento", IsForeignKey=true)]
		public tblDepartamento tblDepartamento
		{
			get
			{
				return this._tblDepartamento.Entity;
			}
			set
			{
				tblDepartamento previousValue = this._tblDepartamento.Entity;
				if (((previousValue != value) 
							|| (this._tblDepartamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblDepartamento.Entity = null;
						previousValue.tblEmpleado.Remove(this);
					}
					this._tblDepartamento.Entity = value;
					if ((value != null))
					{
						value.tblEmpleado.Add(this);
						this._idDepartamento = value.idDepartamento;
					}
					else
					{
						this._idDepartamento = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblDepartamento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblCapacitacion(tblCapacitacion entity)
		{
			this.SendPropertyChanging();
			entity.tblEmpleado = this;
		}
		
		private void detach_tblCapacitacion(tblCapacitacion entity)
		{
			this.SendPropertyChanging();
			entity.tblEmpleado = null;
		}
		
		private void attach_tblDtosFamilia(tblDtosFamilia entity)
		{
			this.SendPropertyChanging();
			entity.tblEmpleado = this;
		}
		
		private void detach_tblDtosFamilia(tblDtosFamilia entity)
		{
			this.SendPropertyChanging();
			entity.tblEmpleado = null;
		}
		
		private void attach_tblReferencia(tblReferencia entity)
		{
			this.SendPropertyChanging();
			entity.tblEmpleado = this;
		}
		
		private void detach_tblReferencia(tblReferencia entity)
		{
			this.SendPropertyChanging();
			entity.tblEmpleado = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblEmpresa")]
	public partial class tblEmpresa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idEmpresa;
		
		private string _nombre;
		
		private string _direccion;
		
		private System.Nullable<int> _idDepartamento;
		
		private EntityRef<tblDepartamento> _tblDepartamento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEmpresaChanging(int value);
    partial void OnidEmpresaChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OnidDepartamentoChanging(System.Nullable<int> value);
    partial void OnidDepartamentoChanged();
    #endregion
		
		public tblEmpresa()
		{
			this._tblDepartamento = default(EntityRef<tblDepartamento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpresa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idEmpresa
		{
			get
			{
				return this._idEmpresa;
			}
			set
			{
				if ((this._idEmpresa != value))
				{
					this.OnidEmpresaChanging(value);
					this.SendPropertyChanging();
					this._idEmpresa = value;
					this.SendPropertyChanged("idEmpresa");
					this.OnidEmpresaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(50)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(50)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepartamento", DbType="Int")]
		public System.Nullable<int> idDepartamento
		{
			get
			{
				return this._idDepartamento;
			}
			set
			{
				if ((this._idDepartamento != value))
				{
					if (this._tblDepartamento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidDepartamentoChanging(value);
					this.SendPropertyChanging();
					this._idDepartamento = value;
					this.SendPropertyChanged("idDepartamento");
					this.OnidDepartamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblDepartamento_tblEmpresa", Storage="_tblDepartamento", ThisKey="idDepartamento", OtherKey="idDepartamento", IsForeignKey=true)]
		public tblDepartamento tblDepartamento
		{
			get
			{
				return this._tblDepartamento.Entity;
			}
			set
			{
				tblDepartamento previousValue = this._tblDepartamento.Entity;
				if (((previousValue != value) 
							|| (this._tblDepartamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblDepartamento.Entity = null;
						previousValue.tblEmpresa.Remove(this);
					}
					this._tblDepartamento.Entity = value;
					if ((value != null))
					{
						value.tblEmpresa.Add(this);
						this._idDepartamento = value.idDepartamento;
					}
					else
					{
						this._idDepartamento = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblDepartamento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblReferencia")]
	public partial class tblReferencia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idReferencia;
		
		private string _nombres;
		
		private System.Nullable<int> _telefono;
		
		private string _tipoReferencia;
		
		private System.Nullable<int> _idEmpleado;
		
		private EntityRef<tblEmpleado> _tblEmpleado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidReferenciaChanging(int value);
    partial void OnidReferenciaChanged();
    partial void OnnombresChanging(string value);
    partial void OnnombresChanged();
    partial void OntelefonoChanging(System.Nullable<int> value);
    partial void OntelefonoChanged();
    partial void OntipoReferenciaChanging(string value);
    partial void OntipoReferenciaChanged();
    partial void OnidEmpleadoChanging(System.Nullable<int> value);
    partial void OnidEmpleadoChanged();
    #endregion
		
		public tblReferencia()
		{
			this._tblEmpleado = default(EntityRef<tblEmpleado>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idReferencia", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idReferencia
		{
			get
			{
				return this._idReferencia;
			}
			set
			{
				if ((this._idReferencia != value))
				{
					this.OnidReferenciaChanging(value);
					this.SendPropertyChanging();
					this._idReferencia = value;
					this.SendPropertyChanged("idReferencia");
					this.OnidReferenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="NVarChar(100)")]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this.OnnombresChanging(value);
					this.SendPropertyChanging();
					this._nombres = value;
					this.SendPropertyChanged("nombres");
					this.OnnombresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="Int")]
		public System.Nullable<int> telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this.OntelefonoChanging(value);
					this.SendPropertyChanging();
					this._telefono = value;
					this.SendPropertyChanged("telefono");
					this.OntelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoReferencia", DbType="NVarChar(100)")]
		public string tipoReferencia
		{
			get
			{
				return this._tipoReferencia;
			}
			set
			{
				if ((this._tipoReferencia != value))
				{
					this.OntipoReferenciaChanging(value);
					this.SendPropertyChanging();
					this._tipoReferencia = value;
					this.SendPropertyChanged("tipoReferencia");
					this.OntipoReferenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpleado", DbType="Int")]
		public System.Nullable<int> idEmpleado
		{
			get
			{
				return this._idEmpleado;
			}
			set
			{
				if ((this._idEmpleado != value))
				{
					if (this._tblEmpleado.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._idEmpleado = value;
					this.SendPropertyChanged("idEmpleado");
					this.OnidEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblEmpleado_tblReferencia", Storage="_tblEmpleado", ThisKey="idEmpleado", OtherKey="idEmpleado", IsForeignKey=true)]
		public tblEmpleado tblEmpleado
		{
			get
			{
				return this._tblEmpleado.Entity;
			}
			set
			{
				tblEmpleado previousValue = this._tblEmpleado.Entity;
				if (((previousValue != value) 
							|| (this._tblEmpleado.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblEmpleado.Entity = null;
						previousValue.tblReferencia.Remove(this);
					}
					this._tblEmpleado.Entity = value;
					if ((value != null))
					{
						value.tblReferencia.Add(this);
						this._idEmpleado = value.idEmpleado;
					}
					else
					{
						this._idEmpleado = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblEmpleado");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Persona")]
	public partial class Tbl_Persona : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _per_id;
		
		private string _per_nombre;
		
		private string _per_apellido;
		
		private System.Nullable<int> _per_cedula;
		
		private string _per_correo;
		
		private System.Nullable<System.DateTime> _per_fch_nacimiento;
		
		private string _per_direccion;
		
		private System.Nullable<System.DateTime> _per_fch_creacion;
		
		private string _per_estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onper_idChanging(int value);
    partial void Onper_idChanged();
    partial void Onper_nombreChanging(string value);
    partial void Onper_nombreChanged();
    partial void Onper_apellidoChanging(string value);
    partial void Onper_apellidoChanged();
    partial void Onper_cedulaChanging(System.Nullable<int> value);
    partial void Onper_cedulaChanged();
    partial void Onper_correoChanging(string value);
    partial void Onper_correoChanged();
    partial void Onper_fch_nacimientoChanging(System.Nullable<System.DateTime> value);
    partial void Onper_fch_nacimientoChanged();
    partial void Onper_direccionChanging(string value);
    partial void Onper_direccionChanged();
    partial void Onper_fch_creacionChanging(System.Nullable<System.DateTime> value);
    partial void Onper_fch_creacionChanged();
    partial void Onper_estadoChanging(string value);
    partial void Onper_estadoChanged();
    #endregion
		
		public Tbl_Persona()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int per_id
		{
			get
			{
				return this._per_id;
			}
			set
			{
				if ((this._per_id != value))
				{
					this.Onper_idChanging(value);
					this.SendPropertyChanging();
					this._per_id = value;
					this.SendPropertyChanged("per_id");
					this.Onper_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_nombre", DbType="VarChar(50)")]
		public string per_nombre
		{
			get
			{
				return this._per_nombre;
			}
			set
			{
				if ((this._per_nombre != value))
				{
					this.Onper_nombreChanging(value);
					this.SendPropertyChanging();
					this._per_nombre = value;
					this.SendPropertyChanged("per_nombre");
					this.Onper_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_apellido", DbType="VarChar(50)")]
		public string per_apellido
		{
			get
			{
				return this._per_apellido;
			}
			set
			{
				if ((this._per_apellido != value))
				{
					this.Onper_apellidoChanging(value);
					this.SendPropertyChanging();
					this._per_apellido = value;
					this.SendPropertyChanged("per_apellido");
					this.Onper_apellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_cedula", DbType="Int")]
		public System.Nullable<int> per_cedula
		{
			get
			{
				return this._per_cedula;
			}
			set
			{
				if ((this._per_cedula != value))
				{
					this.Onper_cedulaChanging(value);
					this.SendPropertyChanging();
					this._per_cedula = value;
					this.SendPropertyChanged("per_cedula");
					this.Onper_cedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_correo", DbType="VarChar(50)")]
		public string per_correo
		{
			get
			{
				return this._per_correo;
			}
			set
			{
				if ((this._per_correo != value))
				{
					this.Onper_correoChanging(value);
					this.SendPropertyChanging();
					this._per_correo = value;
					this.SendPropertyChanged("per_correo");
					this.Onper_correoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_fch_nacimiento", DbType="Date")]
		public System.Nullable<System.DateTime> per_fch_nacimiento
		{
			get
			{
				return this._per_fch_nacimiento;
			}
			set
			{
				if ((this._per_fch_nacimiento != value))
				{
					this.Onper_fch_nacimientoChanging(value);
					this.SendPropertyChanging();
					this._per_fch_nacimiento = value;
					this.SendPropertyChanged("per_fch_nacimiento");
					this.Onper_fch_nacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_direccion", DbType="VarChar(50)")]
		public string per_direccion
		{
			get
			{
				return this._per_direccion;
			}
			set
			{
				if ((this._per_direccion != value))
				{
					this.Onper_direccionChanging(value);
					this.SendPropertyChanging();
					this._per_direccion = value;
					this.SendPropertyChanged("per_direccion");
					this.Onper_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_fch_creacion", DbType="Date")]
		public System.Nullable<System.DateTime> per_fch_creacion
		{
			get
			{
				return this._per_fch_creacion;
			}
			set
			{
				if ((this._per_fch_creacion != value))
				{
					this.Onper_fch_creacionChanging(value);
					this.SendPropertyChanging();
					this._per_fch_creacion = value;
					this.SendPropertyChanged("per_fch_creacion");
					this.Onper_fch_creacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_estado", DbType="Char(2)")]
		public string per_estado
		{
			get
			{
				return this._per_estado;
			}
			set
			{
				if ((this._per_estado != value))
				{
					this.Onper_estadoChanging(value);
					this.SendPropertyChanging();
					this._per_estado = value;
					this.SendPropertyChanged("per_estado");
					this.Onper_estadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tbl_Usuario")]
	public partial class Tbl_Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _usu_id;
		
		private System.Nullable<int> _per_id;
		
		private string _usu_nombre;
		
		private string _usu_contra;
		
		private string _usu_estado;
		
		private System.Nullable<int> _roll_id;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusu_idChanging(int value);
    partial void Onusu_idChanged();
    partial void Onper_idChanging(System.Nullable<int> value);
    partial void Onper_idChanged();
    partial void Onusu_nombreChanging(string value);
    partial void Onusu_nombreChanged();
    partial void Onusu_contraChanging(string value);
    partial void Onusu_contraChanged();
    partial void Onusu_estadoChanging(string value);
    partial void Onusu_estadoChanged();
    partial void Onroll_idChanging(System.Nullable<int> value);
    partial void Onroll_idChanged();
    #endregion
		
		public Tbl_Usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int usu_id
		{
			get
			{
				return this._usu_id;
			}
			set
			{
				if ((this._usu_id != value))
				{
					this.Onusu_idChanging(value);
					this.SendPropertyChanging();
					this._usu_id = value;
					this.SendPropertyChanged("usu_id");
					this.Onusu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_per_id", DbType="Int")]
		public System.Nullable<int> per_id
		{
			get
			{
				return this._per_id;
			}
			set
			{
				if ((this._per_id != value))
				{
					this.Onper_idChanging(value);
					this.SendPropertyChanging();
					this._per_id = value;
					this.SendPropertyChanged("per_id");
					this.Onper_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_nombre", DbType="VarChar(50)")]
		public string usu_nombre
		{
			get
			{
				return this._usu_nombre;
			}
			set
			{
				if ((this._usu_nombre != value))
				{
					this.Onusu_nombreChanging(value);
					this.SendPropertyChanging();
					this._usu_nombre = value;
					this.SendPropertyChanged("usu_nombre");
					this.Onusu_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_contra", DbType="VarChar(50)")]
		public string usu_contra
		{
			get
			{
				return this._usu_contra;
			}
			set
			{
				if ((this._usu_contra != value))
				{
					this.Onusu_contraChanging(value);
					this.SendPropertyChanging();
					this._usu_contra = value;
					this.SendPropertyChanged("usu_contra");
					this.Onusu_contraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usu_estado", DbType="VarChar(10)")]
		public string usu_estado
		{
			get
			{
				return this._usu_estado;
			}
			set
			{
				if ((this._usu_estado != value))
				{
					this.Onusu_estadoChanging(value);
					this.SendPropertyChanging();
					this._usu_estado = value;
					this.SendPropertyChanged("usu_estado");
					this.Onusu_estadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roll_id", DbType="Int")]
		public System.Nullable<int> roll_id
		{
			get
			{
				return this._roll_id;
			}
			set
			{
				if ((this._roll_id != value))
				{
					this.Onroll_idChanging(value);
					this.SendPropertyChanging();
					this._roll_id = value;
					this.SendPropertyChanged("roll_id");
					this.Onroll_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class mostrarCapacitacionResult
	{
		
		private int _ID;
		
		private string _descripcion;
		
		private string _fechaIni;
		
		private string _fechaFin;
		
		private string _Nombres;
		
		public mostrarCapacitacionResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(100)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaIni", DbType="NVarChar(100)")]
		public string fechaIni
		{
			get
			{
				return this._fechaIni;
			}
			set
			{
				if ((this._fechaIni != value))
				{
					this._fechaIni = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fechaFin", DbType="NVarChar(100)")]
		public string fechaFin
		{
			get
			{
				return this._fechaFin;
			}
			set
			{
				if ((this._fechaFin != value))
				{
					this._fechaFin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombres", DbType="NVarChar(100)")]
		public string Nombres
		{
			get
			{
				return this._Nombres;
			}
			set
			{
				if ((this._Nombres != value))
				{
					this._Nombres = value;
				}
			}
		}
	}
	
	public partial class mostrarCargoResult
	{
		
		private int _idCargo;
		
		private string _descripcion;
		
		public mostrarCargoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCargo", DbType="Int NOT NULL")]
		public int idCargo
		{
			get
			{
				return this._idCargo;
			}
			set
			{
				if ((this._idCargo != value))
				{
					this._idCargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(50)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
	}
	
	public partial class mostrarCartgoResult
	{
		
		private int _idCargo;
		
		private string _descripcion;
		
		public mostrarCartgoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCargo", DbType="Int NOT NULL")]
		public int idCargo
		{
			get
			{
				return this._idCargo;
			}
			set
			{
				if ((this._idCargo != value))
				{
					this._idCargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(50)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
	}
	
	public partial class mostrarDepartamentoResult
	{
		
		private int _idDepartamento;
		
		private string _descripcion;
		
		public mostrarDepartamentoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDepartamento", DbType="Int NOT NULL")]
		public int idDepartamento
		{
			get
			{
				return this._idDepartamento;
			}
			set
			{
				if ((this._idDepartamento != value))
				{
					this._idDepartamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="NVarChar(50)")]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
	}
	
	public partial class mostrarDtosFamiliaResult
	{
		
		private int _idDtosFamilia;
		
		private string _nombrePaterno;
		
		private string _nombreMaterno;
		
		private string _direccion;
		
		private System.Nullable<int> _telefono;
		
		private System.Nullable<int> _idEmpleado;
		
		public mostrarDtosFamiliaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idDtosFamilia", DbType="Int NOT NULL")]
		public int idDtosFamilia
		{
			get
			{
				return this._idDtosFamilia;
			}
			set
			{
				if ((this._idDtosFamilia != value))
				{
					this._idDtosFamilia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombrePaterno", DbType="NVarChar(100)")]
		public string nombrePaterno
		{
			get
			{
				return this._nombrePaterno;
			}
			set
			{
				if ((this._nombrePaterno != value))
				{
					this._nombrePaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreMaterno", DbType="NVarChar(100)")]
		public string nombreMaterno
		{
			get
			{
				return this._nombreMaterno;
			}
			set
			{
				if ((this._nombreMaterno != value))
				{
					this._nombreMaterno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(100)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this._direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="Int")]
		public System.Nullable<int> telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this._telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpleado", DbType="Int")]
		public System.Nullable<int> idEmpleado
		{
			get
			{
				return this._idEmpleado;
			}
			set
			{
				if ((this._idEmpleado != value))
				{
					this._idEmpleado = value;
				}
			}
		}
	}
	
	public partial class mostrarEmpleadoResult
	{
		
		private int _ID;
		
		private string _nombres;
		
		private string _direccion;
		
		private string _correo;
		
		private System.Nullable<int> _cedula;
		
		private System.Nullable<int> _telefono;
		
		private string _contra;
		
		private string _Departamento;
		
		private string _Cargo;
		
		public mostrarEmpleadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombres", DbType="NVarChar(100)")]
		public string nombres
		{
			get
			{
				return this._nombres;
			}
			set
			{
				if ((this._nombres != value))
				{
					this._nombres = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(100)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this._direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="NVarChar(100)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this._correo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="Int")]
		public System.Nullable<int> cedula
		{
			get
			{
				return this._cedula;
			}
			set
			{
				if ((this._cedula != value))
				{
					this._cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_telefono", DbType="Int")]
		public System.Nullable<int> telefono
		{
			get
			{
				return this._telefono;
			}
			set
			{
				if ((this._telefono != value))
				{
					this._telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contra", DbType="NVarChar(100)")]
		public string contra
		{
			get
			{
				return this._contra;
			}
			set
			{
				if ((this._contra != value))
				{
					this._contra = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departamento", DbType="NVarChar(50)")]
		public string Departamento
		{
			get
			{
				return this._Departamento;
			}
			set
			{
				if ((this._Departamento != value))
				{
					this._Departamento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cargo", DbType="NVarChar(50)")]
		public string Cargo
		{
			get
			{
				return this._Cargo;
			}
			set
			{
				if ((this._Cargo != value))
				{
					this._Cargo = value;
				}
			}
		}
	}
	
	public partial class mostrarEmpresaResult
	{
		
		private int _ID;
		
		private string _nombre;
		
		private string _direccion;
		
		private string _Departamento;
		
		public mostrarEmpresaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="NVarChar(50)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="NVarChar(50)")]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this._direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departamento", DbType="NVarChar(50)")]
		public string Departamento
		{
			get
			{
				return this._Departamento;
			}
			set
			{
				if ((this._Departamento != value))
				{
					this._Departamento = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
